# Auto-generated from .repo.toml by 'just repo_toml_generate'
# DO NOT EDIT THIS FILE MANUALLY - regenerate with: just repo_toml_generate

# About section
REPO_DESCRIPTION="FINI infrastructure as code 🦺🏛"
REPO_LICENSE=""
REPO_TOPICS="digitalocean,hcl,infrastructure-as-code,opentofu,terraform"

# URLs section
REPO_GIT_SSH="git@github.com:fini-net/fini-infra.git"
REPO_WEB_URL="https://github.com/fini-net/fini-infra"

# Derived values
REPO_ORG_NAME="fini-net"
REPO_REPO_NAME="fini-infra"

# Feature flags (strings: "true" or "false")
FLAG_CLAUDE="true"
FLAG_CLAUDE_REVIEW="true"
FLAG_COPILOT_REVIEW="true"
FLAG_STANDARD_RELEASE="true"

# Topics as array (for iteration)
REPO_TOPICS_ARRAY=(
    "digitalocean"
    "hcl"
    "infrastructure-as-code"
    "opentofu"
    "terraform"
)
