# .repo.toml

[about]
description = "FINI infrastructure as code 🦺🏛"
topics = ["digitalocean", "hcl", "infrastructure-as-code", "opentofu", "terraform"]

[urls]
git_ssh = "git@github.com:fini-net/fini-infra.git"
web_url = "https://github.com/fini-net/fini-infra"

[flags]
claude = true
claude-review = true
copilot-review = true
standard-release = true
