---
name: MarkdownLint
on:
  push:
    branches:
      - main
  pull_request:

# global permissions
permissions: {}

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v19
      with:
        globs: |
          **/*.md
